#!/usr/bin/bash

DESKTOP=${DESKTOP:-"chat"}
FORCE=${FORCE:-"0"}

_termite_loop() {
    NAME=$1 && shift
    COMMAND=$@
    termite --name $NAME -e "sh -c 'while true; do $COMMAND; done'" &
}

if [[ ! $(bspc query --desktops --desktop "$DESKTOP".occupied) || $FORCE -eq 1 ]]; then

    # clean
    
    bspc node @$DESKTOP:/ -k

    # recepticles

    bspc node @$DESKTOP:/ -i

    # rules

    bspc rule --add Termite:slack -o node=@$DESKTOP:/

    # programs
    
    t-loop slack slack-term &
    
fi