#!/usr/bin/bash

DESKTOP=${DESKTOP:-"code"}
FORCE=${FORCE:-"0"}

if [[ ! $(bspc query --desktops --desktop "$DESKTOP".occupied) || $FORCE -eq 1 ]]; then

    # clean
    
    bspc node @$DESKTOP:/ -k

    # recepticles

    bspc node @$DESKTOP:/ -i
    bspc node @$DESKTOP:/ -o 0.25 -p east -i
    bspc node @$DESKTOP:/2 -o 0.66 -p east -i

    # rules

    bspc rule --add "code-oss" -o node=@$DESKTOP:/1
    bspc rule --add "Termite" -o node=@$DESKTOP:/2
    
    # programs

    code
    termite
    # android-messages &
    # slack &
    # whatsapp &
    
fid