#!/usr/bin/bash

DESKTOP=${DESKTOP:-"media"}
FORCE=${FORCE:-"0"}

_termite_loop() {
    NAME=$1 && shift
    COMMAND=$@
    termite --name $NAME -e "sh -c 'while true; do $COMMAND; done'" &
}

if [[ ! $(bspc query --desktops --desktop "$DESKTOP".occupied) || $FORCE -eq 1 ]]; then

    # clean
    
    bspc node @$DESKTOP:/ -k

    # recepticles

    bspc node @$DESKTOP:/ -i
    bspc node @$DESKTOP:/ -o 0.7 -p east -i
    bspc node @$DESKTOP:/ -o 0.7 -p east -i

    # rules

    bspc rule --add Termite:ncspotTerm -o node=@$DESKTOP:/1
    bspc rule --add Termite:bashTerm -o node=@$DESKTOP:/2
    
    # programs

    $BROWSER --app="https://www.youtube.com" &
    $BROWSER --app="https://www.netflix.com" &
    spotify-tray --toggle
    
fi