#!/usr/bin/bash

DESKTOP=${DESKTOP:-"system"}
FORCE=${FORCE:-"0"}

if [[ ! $(bspc query --desktops --desktop "$DESKTOP".occupied) || $FORCE -eq 1 ]]; then

    # clean
    
    bspc node @$DESKTOP:/ -k

    # recepticles

    bspc node @$DESKTOP:/ -i

    # rules

    bspc rule --add Termite:btm -o node=@$DESKTOP:/
    
    # programs
    termite-loop btm "btm"
    
fi