#!/usr/bin/bash

DESKTOP=${DESKTOP:-"system"}
FORCE=${FORCE:-"0"}

_termite_loop() {
    NAME=$1 && shift
    COMMAND=$@
    termite --name $NAME -e "sh -c 'while true; do $COMMAND; done'" &
}

if [[ ! $(bspc query --desktops --desktop "$DESKTOP".occupied) || $FORCE -eq 1 ]]; then

    # clean
    
    bspc node @$DESKTOP:/ -k

    # recepticles

    bspc node @$DESKTOP:/ -i
    # bspc node @$DESKTOP:/ -o 0.80 -p east -i

    # rules

    bspc rule --add Termite:btmTerm -o node=@$DESKTOP:/
    # bspc rule --add Termite:nvtopTerm -o node=@$DESKTOP:/2
    
    # programs
    _termite_loop btmTerm "btm"
    # _termite_loop nvtopTerm "nvtop"
    
fi