import = ["/home/andronics/.config/alacritty/themes/catppuccin-moncha.yml"]

[font]
size = 14.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Light"
title = "Alacritty"

[window.dimensions]
columns = 200
lines = 20

[window.padding]
x = 4
y = 4

[window.position]
x = 0
y = 0
