#!/usr/bin/env bash

# ------------------------------

dotfiles_source_root="$(cd "$(dirname "$0")" && pwd)"
dotfiles_target_root="${HOME}"
dotfiles_ignore="\.((?:pre|post)?(?:un)?install|fold)|README\.md|LICENSE|\.gitignore|\.git|\.DS_Store"

# ------------------------------

err()  { printf '\033[0;31merror:\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[0;33mwarn:\033[0m  %s\n' "$*" >&2; }
info() { printf '\033[0;36m·\033[0m %s\n' "$*"; }
ok()   { printf '\033[0;32m✓\033[0m %s\n' "$*"; }

# ------------------------------

_dotfiles() {

   [[ $# -eq 0 ]] && {
        info "usage: $(basename $0) [i|install] "
        return 1
   }

   _command=$1
   shift 2>/dev/null

   pushd "${dotfiles_source_root}" > /dev/null

   case ${_command} in
      
      i|install) _dotfiles_install "$@" ;;
      r|reinstall) _dotfiles_reinstall "$@" ;;
      u|uninstall) _dotfiles_uninstall "$@" ;;
      
      *) printf "command '%s' unknown" "${_command}" && return ;;

   esac

   popd > /dev/null


}


# ------------------------------

_dotfiles_install() {

   [[ ! -d "${dotfiles_target_root}" ]] && mkdir -p "${dotfiles_target_root}"

   _pkgs=${@:-"*"}

   for _pkg in ${_pkgs}; do
      
      [[ ! -d ${_pkg} ]] && {
         err "package '${_pkg}' does not exist"
         continue
      }
      
      
      [[ ${_pkg} =~ ^\. ]] && {
         warn "package '${_pkg}' prefixed with a period... ignoring"
         continue
      }

      _dotfiles_pre_install

      [[ -f "${_pkg}/.install" && -x "${_pkg}/.install" ]] && {
         info "package '${_pkg}' is being installed by script"
         source "${_pkg}/.install"
      }
      
      [[ ! -f "${_pkg}/.install" ]] && {

         _no_folding="--no-folding"
         
         [[ -f "${_pkg}/.fold" ]] && _no_folding=""

         info "package '${_pkg}' is being installed by stow"
         stow -t "${dotfiles_target_root}" -S ${_pkg} --ignore="${dotfiles_ignore}" ${_no_folding}

         [[ $? -ne 0 ]] && err "... failed to install"

      }

      _dotfiles_post_install

   done

}

# ------------------------------

_dotfiles_pre_install() {

   _script="${dotfiles_source_root}/${_pkg}/.preinstall"
      
   [[ -f "${_script}" && -x "${_script}" ]] && {
      info "package '${_pkg}' executing preinstall script"
      source "${_script}"
   }

}

_dotfiles_pre_uninstall() {

   _script="${dotfiles_source_root}/${_pkg}/.preuninstall"
      
   [[ -f "${_script}" && -x "${_script}" ]] && {
      info "package '${_pkg}' executing preuninstall script"
      source "${_script}"
   }
   
}

_dotfiles_post_install() {

   _script="${dotfiles_source_root}/${_pkg}/.postinstall"
      
   [[ -f "${_script}" && -x "${_script}" ]] && {
      info "package '${_pkg}' executing postinstall script"
      source "${_script}"
   }

}

_dotfiles_post_uninstall() {

   _script="${dotfiles_source_root}/${_pkg}/.postuninstall"
      
   [[ -f "${_script}" && -x "${_script}" ]] && {
      info "package '${_pkg}' executing postuninstall script"
      source "${_script}"
   }
   
}

# ------------------------------

_dotfiles_reinstall() {

   _dotfiles_uninstall $* 
   _dotfiles_install $* 

}

# ------------------------------

_dotfiles_uninstall() {

   [[ ! -d "${dotfiles_target_root}" ]] && return 1

   _pkgs=${@:-"*"}

   for _pkg in ${_pkgs}; do
      
      [[ ! -d ${_pkg} ]] && {
         err "package '${_pkg}' does not exist"
         continue
      }

      [[ ${_pkg} =~ ^\. ]] && {
         warn "package '${_pkg}' prefixed with a period... ignoring"
         continue
      }

      _dotfiles_pre_uninstall
         
      [[ -f "${_pkg}/.uninstall" && -x "${_pkg}/.uninstall" ]] && {
         info "package '${_pkg}' is being uninstalled by script"
         source "${_pkg}/.uninstall"
      }
      
      [[ ! -f "${_pkg}/.uninstall"  && ! -f "${_pkg}/.install" ]] && {

        _no_folding="--no-folding"
         
         [[ -f "${_pkg}/.fold" ]] && _no_folding=""
         
         info "package '${_pkg}' is being uninstalled by stow"
         stow -t "${dotfiles_target_root}" -D ${_pkg} --ignore="${dotfiles_ignore}" ${_no_folding}

         [[ $? -ne 0 ]] && err "... failed to uninstall"

      }

      _dotfiles_post_uninstall

   done

}

# ------------------------------

_dotfiles "$@"

