#!/usr/bin/env zsh

# source "$(which _onexit)"

# ------------------------------

# Desktops

bspc monitor "DP-2" -d 0

# Global Settings
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config click_to_focus button1
bspc config focus_follows_pointer false
bspc config honor_size_hints true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config presel_feedback_color "$(palette overlay0)"

# External Rules
bspc config external_rules_command "$(which bsp-external-rules)"

# Pointer
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Borders
bspc config border_radius 0
bspc config border_width 0
bspc config normal_border_color	"$(palette peach)"
bspc config active_border_color	"$(palette crust)"
bspc config focused_border_color "$(palette sky)"

# Desktop Padding
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 5

# Rules
bspc rule -r "*:*:*"
bspc rule -a Alacritty border=off