#!/bin/sh

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Trap : make sure everything started below is
# signalled when this script exits or dies. Also clean up $state_path.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

on_exit() {        

        for child in $(jobs -p); do
                jobs -p | grep -q $child && kill $child
        done

        # Extra paranoia
        [[ -d "${state_path}" && -w "${state_path}" ]] && rm -rf -- "${state_path}"

}

trap on_exit EXIT QUIT INT 30

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Host Configuration
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


case $(hostname) in
    desktop)
        export HOST_RESOLUTION=${HOST_RESOULTION:-"5120x1440"}
        export MONITOR=${MONITOR:-"DP-2"}
        export WINDOW_GAP=${WINDOWN_GAP:-"20"}
        export WINDOW_PADDING=${WINDOW_PADDING:-"10"}
        ;;
    laptop)
        export HOST_RESOLUTION=${HOST_RESOULTION:-"1600x900"}
        export MONITOR=${MONITOR:-"LVDS1"}
        export WINDOW_GAP=${WINDOWN_GAP:-"20"}
        export WINDOW_PADDING=${WINDOW_PADDING:-"10"}
        ;;
    *) ;;
esac

nvidia-settings --assign CurrentMetaMode="${HOST_RESOLUTION} +0+0 { ForceCompositionPipeline = On, ForceFullCompositionPipeline = On }"

$HOME/.config/bspwm/monitor
$HOME/.config/bspwm/config
$HOME/.config/bspwm/rules

ls -1 $HOME/.config/bspwm/layouts | while read doc; do
    echo $doc
    $HOME/.config/bspwm/layouts/$doc
done