#!/bin/sh

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Global Settings
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config click_to_focus button1

bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config presel_feedback_color "#4c566a"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# External Rules
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc config external_rules_command "$(which bspc-external-rules)"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Pointer
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Borders
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc config border_width 2s
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# Desktop Padding
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc config top_padding $WINDOW_PADDING
bspc config bottom_padding $WINDOW_PADDING
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap $WINDOW_GAP
